version: "2"
services:
    bootstrap:
      networks:
        ethereum:
          aliases:
            - bootstrap
      build: monitored-client-geth
      container_name: bootstrap
      links:
        - statsmon
      entrypoint: /root/start.sh
      command: "--datadir /ethereum/ --networkid 77 --rpc --nodekeyhex 091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --bootnodes enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@localhost:30303"
      ports:
        - 127.0.0.1:30304:30303
        - 127.0.0.1:30304:30303/udp

    eth:
      networks:
          ethereum:
      build: monitored-client-geth
      links: 
        - statsmon
        - bootstrap
      entrypoint: /root/start.sh
      command: "--datadir /ethereum/ --networkid 77 --rpc --bootnodes enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@bootstrap:30303"

    miner:
      networks:
          ethereum:
      build: monitored-client-geth
      links: 
        - statsmon
        - bootstrap
      entrypoint: /root/start.sh
      command: "--datadir /ethereum/ --networkid 77 --rpc --bootnodes enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@bootstrap:30303 --mine --miner.threads 1 --etherbase=0x5d0fd9faf0bd0e1fab538a82c2d0a002b87ea0e1"

    debug:
      networks:
          ethereum:
      build: monitored-client-geth
      container_name: debug
      links: 
        - statsmon
        - bootstrap
      entrypoint: /root/start.sh
      command: "--datadir /ethereum/ --networkid 77 --rpc --bootnodes enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@bootstrap:30303 --debug"

    statsmon:
      networks:
        ethereum:
          aliases:
            - statsmon
      build: eth-netstats
      container_name: statsmon
      environment:
        - WS_SECRET=eth-net-stats-has-a-secret
      ports:
        - "0.0.0.0:3000:3000"

networks:
  ethereum:
    driver: bridge

